"""empty message

Revision ID: 72488d6c9a19
Revises: 78a880420dc0
Create Date: 2021-03-10 11:10:18.990618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72488d6c9a19'
down_revision = '78a880420dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('incomes', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incomes', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
